import Foundation

/// Generates the managed Nginx site configurations used during setup’s pre-TLS and post-TLS phases.
enum NginxTemplate {

    /// Emits the HTTP-only bootstrap config that serves ACME challenges and redirects all other traffic to canonical HTTPS.
    static func bootstrap(context: SetupContext) throws -> String {
        
        let paths = try context.requirePaths()
        
        return """
        # Auto-generated by deployer setup - managed reverse proxy bootstrap config.
        # Rerun deployer setup to regenerate.

        server {
            listen 80;
            listen [::]:80;
            server_name \(context.primaryDomain) \(context.aliasDomain);

            location ^~ /.well-known/acme-challenge/ {
                root \(paths.acmeWebroot);
                default_type text/plain;
                try_files $uri =404;
            }

            location / {
                return 301 https://\(context.primaryDomain)$request_uri;
            }
        }
        """
    }

    /// Emits the full TLS config by reusing the bootstrap HTTP server block and appending HTTPS proxy/application routing blocks.
    static func tls(context: SetupContext) throws -> String {
        
        let paths = try context.requirePaths()
        let bootstrapConfig = try
        
        return """
        \(bootstrapConfig)

        server {
            listen 443 ssl http2;
            listen [::]:443 ssl http2;
            server_name \(context.aliasDomain);

            ssl_certificate /etc/letsencrypt/live/\(context.certName)/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/\(context.certName)/privkey.pem;
            return 301 https://\(context.primaryDomain)$request_uri;
        }

        server {
            listen 443 ssl http2;
            listen [::]:443 ssl http2;
            server_name \(context.primaryDomain);

            root \(paths.appPublicDirectory);
            index index.html;

            ssl_certificate /etc/letsencrypt/live/\(context.certName)/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/\(context.certName)/privkey.pem;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_session_timeout 1d;
            ssl_session_cache shared:deployer_tls:10m;

            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

            location = \(paths.deployerSocketPath) {
                proxy_pass http://127.0.0.1:\(context.deployerPort);
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 300s;
            }

            location = \(context.panelRoute) {
                proxy_pass http://127.0.0.1:\(context.deployerPort);
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location ^~ \(context.panelRoute)/ {
                proxy_pass http://127.0.0.1:\(context.deployerPort);
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location = \(paths.webhookPath) {
                proxy_pass http://127.0.0.1:\(context.deployerPort);
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location / {
                try_files $uri $uri/ @app_upstream;
            }

            location @app_upstream {
                proxy_pass http://127.0.0.1:\(context.appPort);
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 300s;
            }
        }
        """
    }

    static func renewHookScript() -> String {
        """
        #!/usr/bin/env bash
        set -Eeuo pipefail
        nginx -t
        systemctl reload nginx
        """
    }

}
