import Foundation

extension DeployerctlTemplate {
    
    /// Emits the root helper used by panel-spawned updates to refresh only the deployerctl artifacts.
    static func refreshScript(context: DeployerctlInstallContext) -> String {
        """
        #!/usr/bin/env bash
        set -Eeuo pipefail

        SERVICE_USER=\(q(context.serviceUser))
        INSTALL_DIR=\(q(context.installDirectory))
        WRAPPER_SRC="${INSTALL_DIR}/\(DeployerctlInstaller.stagedWrapperName)"
        CONFIG_SRC="${INSTALL_DIR}/\(DeployerctlInstaller.stagedConfigName)"
        WRAPPER_DST=\(q(context.deployerctlBinary))
        CONFIG_DIR=\(q(context.deployerctlConfigDirectory))
        CONFIG_DST=\(q(context.deployerctlConfig))

        die() { printf 'deployerctl-refresh: error: %s\\n' "$*" >&2; exit 1; }

        require_source() {
        local path="$1"
        [[ -f "$path" && ! -L "$path" ]] || die "staged source is not a regular file: $path"
        local owner
        owner="$(stat -c '%U' "$path")" || die "could not stat staged source: $path"
        [[ "$owner" == "$SERVICE_USER" || "$owner" == "root" ]] || die "unexpected owner for $path: $owner"
        }

        require_source "$WRAPPER_SRC"
        require_source "$CONFIG_SRC"

        install -d -m 0755 -o root -g root "$CONFIG_DIR"
        install -m 0644 -o root -g root "$CONFIG_SRC" "$CONFIG_DST"
        install -m 0755 -o root -g root "$WRAPPER_SRC" "$WRAPPER_DST"
        rm -f -- "$WRAPPER_SRC" "$CONFIG_SRC"
        """
    }
    
    /// Emits the sudoers rule granting the service user access to the narrow refresh helper only.
    static func refreshSudoers(context: DeployerctlInstallContext) -> String {
        """
        # Auto-generated by Vapor-Deployer. Allows panel updates to refresh deployerctl only.
        \(context.serviceUser) ALL=(root) NOPASSWD: \(context.deployerctlRefreshHelper)
        """
    }
    
}
