import Foundation

/// Generates the `deployerctl` configuration and scripts used to control setup-managed services after provisioning.
enum DeployerctlTemplate {
    
    /// Template escaping helper.
    static func q(_ value: String) -> String { value.shellQuoted }
    
    /// Emits a shell-safe key/value configuration consumed by `deployerctl` so runtime commands stay decoupled from setup internals.
    static func configuration(context: DeployerctlInstaller.Context) -> String {
        """
        # Auto-generated by Vapor-Deployer deployer setup/update
        # Consumed by \(context.deployerctlBinary). Rerun deployer setup or update to regenerate.
        SERVICE_USER=\(q(context.serviceUser))
        SERVICE_BACKEND=\(q(context.serviceBackend))
        PRODUCT_NAME=\(q(context.productName))
        APP_NAME=\(q(context.appName))
        APP_REPO_URL=\(q(context.appRepositoryURL))
        APP_PORT=\(q(context.appPort))
        TLS_CONTACT_EMAIL=\(q(context.tlsContactEmail))
        INSTALL_DIR=\(q(context.installDirectory))
        APP_DIR=\(q(context.appDirectory))
        DEPLOYER_LOG=\(q(context.deployerLog))
        APP_LOG=\(q(context.appLog))
        PRIMARY_DOMAIN=\(q(context.primaryDomain))
        ALIAS_DOMAIN=\(q(context.aliasDomain))
        CERT_NAME=\(q(context.certName))
        NGINX_SITE_NAME=\(q(context.nginxSiteName))
        NGINX_SITE_AVAILABLE=\(q(context.nginxSiteAvailable))
        NGINX_SITE_ENABLED=\(q(context.nginxSiteEnabled))
        ACME_WEBROOT=\(q(context.acmeWebroot))
        CERTBOT_RENEW_HOOK=\(q(context.certbotRenewHook))
        WEBHOOK_PATH=\(q(context.webhookPath))
        GITHUB_WEBHOOK_SETTINGS_URL=\(q(context.githubWebhookSettingsURL))
        BUILD_FROM_SOURCE=\(q(context.buildFromSource))
        """
    }
    
}
