import Foundation

/// Generates the `deployerctl` operator config and wrapper script used to control setup-managed services after provisioning.
enum DeployerctlTemplate {

    /// Emits a shell-safe key/value config consumed by `deployerctl` so runtime commands stay decoupled from setup internals.
    static func wrapperConfig(context: SetupContext) throws -> String {
        
        let paths = try context.requirePaths()
        let q = TemplateEscaping.shellLiteral
        
        return """
        # Auto-generated by Vapor-Deployer deployer setup
        # Consumed by \(paths.deployerctlBinary). Rerun deployer setup to regenerate.
        SERVICE_USER=\(q(context.serviceUser))
        SERVICE_MANAGER=\(q(context.serviceManagerKind.rawValue))
        PRODUCT_NAME=\(q(context.productName))
        APP_NAME=\(q(context.appName))
        APP_REPO_URL=\(q(context.appRepositoryURL))
        APP_PORT=\(q(String(context.appPort)))
        TLS_CONTACT_EMAIL=\(q(context.tlsContactEmail))
        INSTALL_DIR=\(q(paths.installDirectory))
        APP_DIR=\(q(paths.appDirectory))
        DEPLOYER_LOG=\(q(paths.deployerLog))
        APP_LOG=\(q("\(paths.appDeployDirectory)/\(context.productName).log"))
        PRIMARY_DOMAIN=\(q(context.primaryDomain))
        ALIAS_DOMAIN=\(q(context.aliasDomain))
        CERT_NAME=\(q(context.certName))
        NGINX_SITE_NAME=\(q(paths.nginxSiteName))
        NGINX_SITE_AVAILABLE=\(q(paths.nginxSiteAvailable))
        NGINX_SITE_ENABLED=\(q(paths.nginxSiteEnabled))
        ACME_WEBROOT=\(q(paths.acmeWebroot))
        CERTBOT_RENEW_HOOK=\(q(paths.certbotRenewHook))
        WEBHOOK_PATH=\(q(paths.webhookPath))
        GITHUB_WEBHOOK_SETTINGS_URL=\(q("https://github.com/\(context.githubOwner)/\(context.githubRepo)/settings/hooks"))
        """
    }

    /// Emits a self-contained `deployerctl` script that normalizes service control across systemd-user and supervisor installs.
    static func wrapperScript() -> String {
        
        """
        #!/usr/bin/env bash
        # deployerctl - operator control surface for the Vapor-Deployer install.
        #
        # Auto-generated by deployer setup. Do not edit by hand; rerun deployer setup to update.

        set -Eeuo pipefail

        CONFIG_FILE="/etc/deployer/deployerctl.conf"
        PROG="$(basename -- "$0")"

        die()  { printf '%s: error: %s\\n' "$PROG" "$*" >&2; exit 1; }
        warn() { printf '%s: %s\\n'        "$PROG" "$*" >&2; }

        usage() {
          cat <<USAGE
        $PROG - control the deployer and its managed app

        Usage:
          sudo $PROG <action> [target]
          sudo $PROG help

        Actions:
          status        Show service status
          start         Start services
          stop          Stop services
          restart       Restart services
          reload        Reload services where supported
          enable        Enable services at boot
          disable       Disable services at boot
          logs          Follow on-disk service log file(s) (Ctrl-C to exit)
          journal       Show recent systemd journal entries (systemd only)
          setup         Rerun deployer setup (interactive)
          update        Update the deployer and redeploy the app (interactive)
          remove        Tear down the entire deployer installation (interactive)

        Targets:
          deployer      Just the deployer service
          app           Just the managed app service (${PRODUCT_NAME:-configured app})
          all           Both services (default)

        Environment:
          NO_COLOR      Disable ANSI colors when set.

        Config file:   $CONFIG_FILE
        USAGE
        }

        case "${1:-}" in
          ""|-h|--help|help) usage; [[ -n "${1:-}" ]] || exit 2; exit 0 ;;
        esac

        [[ $EUID -eq 0 ]] || die "must be run as root (try: sudo $PROG $*)"

        # lifecycle actions are handled before config sourcing so they work in degraded states
        if [[ "${1:-}" == "setup" || "${1:-}" == "remove" || "${1:-}" == "update" ]]; then
          if [[ -r "$CONFIG_FILE" ]]; then
            . "$CONFIG_FILE"
            exec "${INSTALL_DIR:-/home/vapor/deployer}/deployer" "$1"
          else
            exec /home/vapor/deployer/deployer "$1"
          fi
        fi

        [[ -r "$CONFIG_FILE" ]] || die "config not found: $CONFIG_FILE (reinstall with deployer setup)"

        # shellcheck disable=SC1090
        . "$CONFIG_FILE"

        for _var in SERVICE_USER SERVICE_MANAGER PRODUCT_NAME INSTALL_DIR APP_DIR DEPLOYER_LOG APP_LOG; do
          [[ -n "${!_var:-}" ]] || die "missing $_var in $CONFIG_FILE"
        done

        id -u "$SERVICE_USER" >/dev/null 2>&1 || die "service user '$SERVICE_USER' does not exist"
        SERVICE_UID="$(id -u "$SERVICE_USER")"
        BUS_PATH="/run/user/$SERVICE_UID/bus"

        action="$1"; shift
        target="${1:-all}"
        case "$target" in
          deployer|app|all) ;;
          *) warn "unknown target: $target"; usage >&2; exit 2 ;;
        esac

        declare -a units supervisor_progs logs_files
        case "$target" in
          deployer)
            units=("deployer.service")
            supervisor_progs=("deployer")
            logs_files=("$DEPLOYER_LOG")
            ;;
          app)
            units=("${PRODUCT_NAME}.service")
            supervisor_progs=("$PRODUCT_NAME")
            logs_files=("$APP_LOG")
            ;;
          all)
            units=("deployer.service" "${PRODUCT_NAME}.service")
            supervisor_progs=("deployer" "$PRODUCT_NAME")
            logs_files=("$DEPLOYER_LOG" "$APP_LOG")
            ;;
        esac

        ensure_user_manager() {
          loginctl enable-linger "$SERVICE_USER" >/dev/null 2>&1 || true
          systemctl start "user@${SERVICE_UID}.service" >/dev/null 2>&1 || true

          local i
          for ((i = 0; i < 50; i++)); do
            [[ -S "$BUS_PATH" ]] && return 0
            sleep 0.1
          done
          die "user bus $BUS_PATH is unavailable; check 'systemctl status user@${SERVICE_UID}.service'"
        }

        as_service_user() {
          runuser -u "$SERVICE_USER" -- env \
            "XDG_RUNTIME_DIR=/run/user/$SERVICE_UID" \
            "DBUS_SESSION_BUS_ADDRESS=unix:path=$BUS_PATH" \
            "$@"
        }

        user_systemctl()  { as_service_user systemctl  --user "$@"; }
        user_journalctl() { as_service_user journalctl --user "$@"; }

        trap 'exit 130' INT

        case "$SERVICE_MANAGER" in
          systemd)
            case "$action" in
              status)
                ensure_user_manager
                user_systemctl --no-pager status "${units[@]}"
                ;;
              start|stop|restart|reload|enable|disable)
                ensure_user_manager
                user_systemctl "$action" "${units[@]}"
                ;;
              logs)
                _missing=0
                for _f in "${logs_files[@]}"; do
                  [[ -f "$_f" ]] || { warn "log file not found yet: $_f"; _missing=1; }
                done
                (( _missing == 0 )) || warn "run '$PROG journal $target' to see systemd lifecycle events instead"
                exec tail -n 100 -F -- "${logs_files[@]}"
                ;;
              journal)
                ensure_user_manager
                _jargs=()
                for _u in "${units[@]}"; do
                  _jargs+=(--unit "$_u")
                done
                user_journalctl --no-pager --lines=200 "${_jargs[@]}"
                ;;
              *) warn "unknown action: $action"; usage >&2; exit 2 ;;
            esac
            ;;
          supervisor)
            command -v supervisorctl >/dev/null 2>&1 || die "supervisorctl not found on PATH"
            case "$action" in
              status)  supervisorctl status "${supervisor_progs[@]}" ;;
              start)   supervisorctl start  "${supervisor_progs[@]}" ;;
              stop)    supervisorctl stop   "${supervisor_progs[@]}" ;;
              restart|reload) supervisorctl restart "${supervisor_progs[@]}" ;;
              enable|disable)
                die "'$action' is not supported with service manager 'supervisor'"
                ;;
              logs)
                if (( ${#supervisor_progs[@]} == 1 )); then
                  exec supervisorctl tail -f "${supervisor_progs[0]}"
                else
                  exec tail -n 100 -F -- "${logs_files[@]}"
                fi
                ;;
              journal)
                die "'journal' is only available with service manager 'systemd'"
                ;;
              *) warn "unknown action: $action"; usage >&2; exit 2 ;;
            esac
            ;;
          *) die "unknown SERVICE_MANAGER in $CONFIG_FILE: $SERVICE_MANAGER" ;;
        esac
        """
    }

}
